spring.application.name=job-tracker
spring.docker.compose.enabled=false


spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=jobtracker
spring.datasource.password=jobtracker
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
